// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-eofAqrifYTXNC8nuUkgVVhMgkB_cyI8',
    appId: '1:82112618151:web:f71578f51875bb9f928582',
    messagingSenderId: '82112618151',
    projectId: 'timeboxing-67803',
    authDomain: 'timeboxing-67803.firebaseapp.com',
    storageBucket: 'timeboxing-67803.firebasestorage.app',
    measurementId: 'G-MLK3GXDS9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBRBuNC1GJXz-jkB_gJRWvKz52wZ_dHYQ',
    appId: '1:82112618151:android:68d309e5c209e587928582',
    messagingSenderId: '82112618151',
    projectId: 'timeboxing-67803',
    storageBucket: 'timeboxing-67803.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYEhht3rnYpR_H-g0Ifr6lbSTTygsQPtU',
    appId: '1:82112618151:ios:ecaf9e979a6c7ac0928582',
    messagingSenderId: '82112618151',
    projectId: 'timeboxing-67803',
    storageBucket: 'timeboxing-67803.firebasestorage.app',
    iosBundleId: 'com.example.timeboxing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYEhht3rnYpR_H-g0Ifr6lbSTTygsQPtU',
    appId: '1:82112618151:ios:ecaf9e979a6c7ac0928582',
    messagingSenderId: '82112618151',
    projectId: 'timeboxing-67803',
    storageBucket: 'timeboxing-67803.firebasestorage.app',
    iosBundleId: 'com.example.timeboxing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-eofAqrifYTXNC8nuUkgVVhMgkB_cyI8',
    appId: '1:82112618151:web:fcd06f440da251b6928582',
    messagingSenderId: '82112618151',
    projectId: 'timeboxing-67803',
    authDomain: 'timeboxing-67803.firebaseapp.com',
    storageBucket: 'timeboxing-67803.firebasestorage.app',
    measurementId: 'G-0WK9ND3M3Y',
  );
}
