// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5GkKHTtmodZgHHjgc1Gy6IYz1EToo9uc',
    appId: '1:452010596474:web:e7b004d1be9b5ce6d643c3',
    messagingSenderId: '452010596474',
    projectId: 'timebox-bc28a',
    authDomain: 'timebox-bc28a.firebaseapp.com',
    storageBucket: 'timebox-bc28a.firebasestorage.app',
    measurementId: 'G-G0LGZPXE6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4WV4P1p24JubN54F8BVGB0FxZRPLbmM8',
    appId: '1:452010596474:android:0fd7345b45f363c1d643c3',
    messagingSenderId: '452010596474',
    projectId: 'timebox-bc28a',
    storageBucket: 'timebox-bc28a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZbetxj4QCwhb89NgcxPDtyPHI35036Xc',
    appId: '1:452010596474:ios:1f5c5193512b00ffd643c3',
    messagingSenderId: '452010596474',
    projectId: 'timebox-bc28a',
    storageBucket: 'timebox-bc28a.firebasestorage.app',
    iosClientId: '452010596474-lhf8t271an465pm9a3sqk5is30ucuu8m.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeboxing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZbetxj4QCwhb89NgcxPDtyPHI35036Xc',
    appId: '1:452010596474:ios:1f5c5193512b00ffd643c3',
    messagingSenderId: '452010596474',
    projectId: 'timebox-bc28a',
    storageBucket: 'timebox-bc28a.firebasestorage.app',
    iosClientId: '452010596474-lhf8t271an465pm9a3sqk5is30ucuu8m.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeboxing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5GkKHTtmodZgHHjgc1Gy6IYz1EToo9uc',
    appId: '1:452010596474:web:adb02469666b2afbd643c3',
    messagingSenderId: '452010596474',
    projectId: 'timebox-bc28a',
    authDomain: 'timebox-bc28a.firebaseapp.com',
    storageBucket: 'timebox-bc28a.firebasestorage.app',
    measurementId: 'G-CGPPG0RQ9Y',
  );
}
